name: Release

run-name: Release ${{ inputs.releaseVersion }}.${{ inputs.releaseBuild }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        default: '2.14'
      releaseBuild:
        description: 'Release build (e.g. 8)'
        required: true
        default: '0'

jobs:
  release:
    name: Release on Sonatype OSS ${{ github.event.inputs.releaseVersion }}.${{ github.event.inputs.releaseBuild }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Configure Git User
        run: |
          git config user.email ${{ secrets.GIT_CONFIG_EMAIL }}
          git config user.name "RWS Artifact Publishers"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'dummy'

      - name: Release
        env:
          RELEASE: ${{ github.event.inputs.releaseVersion }}.${{ github.event.inputs.releaseBuild }}
          SNAPSHOT: ${{ github.event.inputs.releaseVersion }}-SNAPSHOT
          TAG: release/${{ github.event.inputs.releaseVersion }}/${{ github.event.inputs.releaseVersion }}.${{ github.event.inputs.releaseBuild }}
          # Suppress logging during release prep/perform
          LOGGING: org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: |
          echo "::group::Prepare"
          mvn --batch-mode --no-transfer-progress release:prepare -DreleaseVersion=${{ env.RELEASE }} \
            -DdevelopmentVersion=${{ env.SNAPSHOT }} -Dtag=${{ env.TAG }} \
            -D${{ env.LOGGING }}
          echo "::endgroup::"

          echo "::group::Perform"
          mvn --batch-mode --no-transfer-progress release:perform -DreleaseVersion=${{ env.RELEASE }} \
            -DdevelopmentVersion=${{ env.SNAPSHOT }} -Dtag=${{ env.TAG }} \
            -D${{ env.LOGGING }}
          echo "::endgroup::"
